name: Stylelint (CSS)
on: [push]

jobs:
  linters:
    name: stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions-hub/stylelint@master
        env:
          PATTERN: "*.css"
          # Optional: Specify indentation if your config doesn't handle it
          # INDENT_SPACES: 2

  validators:
    name: HTML5Validator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: .
